#!/usr/bin/env bash
# Usage: docks connect <CONTAINER ID/NAME>
# Summary: Connects a terminal a running container
set -e

if [ $# -eq 2 ]; then
  docker exec -ti $1 $2
elif [ $# -eq 1 ]; then
  docker exec -ti $(docker ps -lq) $1
else
  docker exec -ti ${1:-$(docker ps -lq)} /bin/bash
fi
