#!/usr/bin/env bash
# Usage: docks build <IMAGE NAME/TAG>
# Summary: Builds a container with the given name/tag, assuming a local context '.'
set -e

if [ $# -ne 1 ]; then
  exec docks-help build
  exit
fi

docker build -t $1 .
