#!/usr/bin/env bash
# Usage: docks connect <CONTAINER ID/NAME>
# Summary: Connects a terminal a running container
set -e

if [ $# -ne 1 ]; then
  exec docks-help connect
  exit
fi

docker exec -ti $1 /bin/bash
